#include <stddef.h>
#include <stdint.h>

#include <tianole/input.h>
#include <tianole/tty.h>

struct tty_keymap_entry {
	uint16_t code;
	uint32_t normal;
	uint32_t shifted;
	uint16_t type;
	uint8_t flags;
};

#define TTY_KEYMAP_LETTER 1u

static const struct tty_keymap_entry us_keymap[] = {
	{INPUT_KEY_A, 'a', 'A', TTY_KEYSYM_UNICODE, TTY_KEYMAP_LETTER},
	{INPUT_KEY_B, 'b', 'B', TTY_KEYSYM_UNICODE, TTY_KEYMAP_LETTER},
	{INPUT_KEY_C, 'c', 'C', TTY_KEYSYM_UNICODE, TTY_KEYMAP_LETTER},
	{INPUT_KEY_D, 'd', 'D', TTY_KEYSYM_UNICODE, TTY_KEYMAP_LETTER},
	{INPUT_KEY_E, 'e', 'E', TTY_KEYSYM_UNICODE, TTY_KEYMAP_LETTER},
	{INPUT_KEY_F, 'f', 'F', TTY_KEYSYM_UNICODE, TTY_KEYMAP_LETTER},
	{INPUT_KEY_G, 'g', 'G', TTY_KEYSYM_UNICODE, TTY_KEYMAP_LETTER},
	{INPUT_KEY_H, 'h', 'H', TTY_KEYSYM_UNICODE, TTY_KEYMAP_LETTER},
	{INPUT_KEY_I, 'i', 'I', TTY_KEYSYM_UNICODE, TTY_KEYMAP_LETTER},
	{INPUT_KEY_J, 'j', 'J', TTY_KEYSYM_UNICODE, TTY_KEYMAP_LETTER},
	{INPUT_KEY_K, 'k', 'K', TTY_KEYSYM_UNICODE, TTY_KEYMAP_LETTER},
	{INPUT_KEY_L, 'l', 'L', TTY_KEYSYM_UNICODE, TTY_KEYMAP_LETTER},
	{INPUT_KEY_M, 'm', 'M', TTY_KEYSYM_UNICODE, TTY_KEYMAP_LETTER},
	{INPUT_KEY_N, 'n', 'N', TTY_KEYSYM_UNICODE, TTY_KEYMAP_LETTER},
	{INPUT_KEY_O, 'o', 'O', TTY_KEYSYM_UNICODE, TTY_KEYMAP_LETTER},
	{INPUT_KEY_P, 'p', 'P', TTY_KEYSYM_UNICODE, TTY_KEYMAP_LETTER},
	{INPUT_KEY_Q, 'q', 'Q', TTY_KEYSYM_UNICODE, TTY_KEYMAP_LETTER},
	{INPUT_KEY_R, 'r', 'R', TTY_KEYSYM_UNICODE, TTY_KEYMAP_LETTER},
	{INPUT_KEY_S, 's', 'S', TTY_KEYSYM_UNICODE, TTY_KEYMAP_LETTER},
	{INPUT_KEY_T, 't', 'T', TTY_KEYSYM_UNICODE, TTY_KEYMAP_LETTER},
	{INPUT_KEY_U, 'u', 'U', TTY_KEYSYM_UNICODE, TTY_KEYMAP_LETTER},
	{INPUT_KEY_V, 'v', 'V', TTY_KEYSYM_UNICODE, TTY_KEYMAP_LETTER},
	{INPUT_KEY_W, 'w', 'W', TTY_KEYSYM_UNICODE, TTY_KEYMAP_LETTER},
	{INPUT_KEY_X, 'x', 'X', TTY_KEYSYM_UNICODE, TTY_KEYMAP_LETTER},
	{INPUT_KEY_Y, 'y', 'Y', TTY_KEYSYM_UNICODE, TTY_KEYMAP_LETTER},
	{INPUT_KEY_Z, 'z', 'Z', TTY_KEYSYM_UNICODE, TTY_KEYMAP_LETTER},
	{INPUT_KEY_0, '0', ')', TTY_KEYSYM_UNICODE, 0},
	{INPUT_KEY_1, '1', '!', TTY_KEYSYM_UNICODE, 0},
	{INPUT_KEY_2, '2', '@', TTY_KEYSYM_UNICODE, 0},
	{INPUT_KEY_3, '3', '#', TTY_KEYSYM_UNICODE, 0},
	{INPUT_KEY_4, '4', '$', TTY_KEYSYM_UNICODE, 0},
	{INPUT_KEY_5, '5', '%', TTY_KEYSYM_UNICODE, 0},
	{INPUT_KEY_6, '6', '^', TTY_KEYSYM_UNICODE, 0},
	{INPUT_KEY_7, '7', '&', TTY_KEYSYM_UNICODE, 0},
	{INPUT_KEY_8, '8', '*', TTY_KEYSYM_UNICODE, 0},
	{INPUT_KEY_9, '9', '(', TTY_KEYSYM_UNICODE, 0},
	{INPUT_KEY_ENTER, '\n', '\n', TTY_KEYSYM_UNICODE, 0},
	{INPUT_KEY_BACKSPACE, '\b', '\b', TTY_KEYSYM_UNICODE, 0},
	{INPUT_KEY_TAB, '\t', '\t', TTY_KEYSYM_UNICODE, 0},
	{INPUT_KEY_SPACE, ' ', ' ', TTY_KEYSYM_UNICODE, 0},
	{INPUT_KEY_MINUS, '-', '_', TTY_KEYSYM_UNICODE, 0},
	{INPUT_KEY_EQUAL, '=', '+', TTY_KEYSYM_UNICODE, 0},
	{INPUT_KEY_LEFTBRACE, '[', '{', TTY_KEYSYM_UNICODE, 0},
	{INPUT_KEY_RIGHTBRACE, ']', '}', TTY_KEYSYM_UNICODE, 0},
	{INPUT_KEY_BACKSLASH, '\\', '|', TTY_KEYSYM_UNICODE, 0},
	{INPUT_KEY_SEMICOLON, ';', ':', TTY_KEYSYM_UNICODE, 0},
	{INPUT_KEY_APOSTROPHE, '\'', '"', TTY_KEYSYM_UNICODE, 0},
	{INPUT_KEY_GRAVE, '`', '~', TTY_KEYSYM_UNICODE, 0},
	{INPUT_KEY_COMMA, ',', '<', TTY_KEYSYM_UNICODE, 0},
	{INPUT_KEY_DOT, '.', '>', TTY_KEYSYM_UNICODE, 0},
	{INPUT_KEY_SLASH, '/', '?', TTY_KEYSYM_UNICODE, 0},
	{INPUT_KEY_F1, TTY_FUNC_F1, TTY_FUNC_F11, TTY_KEYSYM_FUNCTION, 0},
	{INPUT_KEY_F2, TTY_FUNC_F2, TTY_FUNC_F12, TTY_KEYSYM_FUNCTION, 0},
	{INPUT_KEY_F3, TTY_FUNC_F3, TTY_FUNC_F3, TTY_KEYSYM_FUNCTION, 0},
	{INPUT_KEY_F4, TTY_FUNC_F4, TTY_FUNC_F4, TTY_KEYSYM_FUNCTION, 0},
	{INPUT_KEY_F5, TTY_FUNC_F5, TTY_FUNC_F5, TTY_KEYSYM_FUNCTION, 0},
	{INPUT_KEY_F6, TTY_FUNC_F6, TTY_FUNC_F6, TTY_KEYSYM_FUNCTION, 0},
	{INPUT_KEY_F7, TTY_FUNC_F7, TTY_FUNC_F7, TTY_KEYSYM_FUNCTION, 0},
	{INPUT_KEY_F8, TTY_FUNC_F8, TTY_FUNC_F8, TTY_KEYSYM_FUNCTION, 0},
	{INPUT_KEY_F9, TTY_FUNC_F9, TTY_FUNC_F9, TTY_KEYSYM_FUNCTION, 0},
	{INPUT_KEY_F10, TTY_FUNC_F10, TTY_FUNC_F10, TTY_KEYSYM_FUNCTION, 0},
	{INPUT_KEY_F11, TTY_FUNC_F11, TTY_FUNC_F11, TTY_KEYSYM_FUNCTION, 0},
	{INPUT_KEY_F12, TTY_FUNC_F12, TTY_FUNC_F12, TTY_KEYSYM_FUNCTION, 0},
	{INPUT_KEY_HOME, TTY_FUNC_HOME, TTY_FUNC_HOME, TTY_KEYSYM_FUNCTION, 0},
	{INPUT_KEY_INSERT,
		TTY_FUNC_INSERT,
		TTY_FUNC_INSERT,
		TTY_KEYSYM_FUNCTION,
		0},
	{INPUT_KEY_DELETE,
		TTY_FUNC_DELETE,
		TTY_FUNC_DELETE,
		TTY_KEYSYM_FUNCTION,
		0},
	{INPUT_KEY_END, TTY_FUNC_END, TTY_FUNC_END, TTY_KEYSYM_FUNCTION, 0},
	{INPUT_KEY_PAGEUP,
		TTY_FUNC_PAGEUP,
		TTY_FUNC_PAGEUP,
		TTY_KEYSYM_FUNCTION,
		0},
	{INPUT_KEY_PAGEDOWN,
		TTY_FUNC_PAGEDOWN,
		TTY_FUNC_PAGEDOWN,
		TTY_KEYSYM_FUNCTION,
		0},
	{INPUT_KEY_UP, TTY_FUNC_UP, TTY_FUNC_UP, TTY_KEYSYM_FUNCTION, 0},
	{INPUT_KEY_DOWN, TTY_FUNC_DOWN, TTY_FUNC_DOWN, TTY_KEYSYM_FUNCTION, 0},
	{INPUT_KEY_LEFT, TTY_FUNC_LEFT, TTY_FUNC_LEFT, TTY_KEYSYM_FUNCTION, 0},
	{INPUT_KEY_RIGHT,
		TTY_FUNC_RIGHT,
		TTY_FUNC_RIGHT,
		TTY_KEYSYM_FUNCTION,
		0},
};

int tty_key_event_to_keysym(
	uint16_t code, uint32_t modifiers, struct tty_keysym *sym)
{
	size_t index;
	int shifted = (modifiers & INPUT_MODIFIER_SHIFT) != 0;
	int caps = (modifiers & INPUT_MODIFIER_CAPSLOCK) != 0;

	if (sym == 0) {
		return 0;
	}

	for (index = 0; index < sizeof(us_keymap) / sizeof(us_keymap[0]);
		index++) {
		if (us_keymap[index].code != code) {
			continue;
		}

		if ((us_keymap[index].flags & TTY_KEYMAP_LETTER) != 0) {
			shifted = shifted != caps;
		}

		sym->type = us_keymap[index].type;
		sym->value = shifted != 0 ? us_keymap[index].shifted
					  : us_keymap[index].normal;
		return 1;
	}

	return 0;
}
