drivers-y := \
	input/input.o \
	input/keyboard/ps2.o \
	tty/keymap.o \
	tty/tty.o \
	video/fbdev/core/fbcon.o \
	video/fbdev/core/font.o

DRIVER_OBJS := $(addprefix $(BUILD_DIR)/drivers/,$(drivers-y))
